#include "TROOT.h"
#include "TFile.h"
#include "TTree.h"
#include "TBrowser.h"
#include "TH2.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <TH1F.h>
#include "TGaxis.h"
#include <TMath.h>
#include <fstream>
#include <iostream>

void PKplustreeTot(){
    Float_t runnum, evnum, helicity,  e_p, eta1, eta, e_phi, Q2, W, phi2, phi1, x, y, zeta, xF, pT1, pT2, Delta_phi, z1, z2, xF1, xF2, pTpT, Mx1, Mx2, Delta_eta, p1_p, p2_p, vz_e,vz_p1,vz_p2, eta2, Mx;


    FILE *fp = fopen("PKTotal.txt","r");
    TFile *hfile = hfile = TFile::Open("PKplus2.root","RECREATE");

    TTree *outTree = new TTree("T","kinematics tree");


    outTree->Branch("runnum",&runnum,"runnum/F");
    outTree->Branch("evnum",&evnum,"evnum/F");
    outTree->Branch("helicity", &helicity,"helicity/F");
    outTree->Branch("e_p",&e_p,"e_p/F");
    outTree->Branch("eta1",&eta1,"eta1/F");
    outTree->Branch("eta",&eta,"eta/F");
    outTree->Branch("e_phi",&e_phi,"e_phi/F");
    outTree->Branch("Q2",&Q2,"Q2/F");
    outTree->Branch("W",&W,"W/F");
    outTree->Branch("phi2",&phi2,"phi2/F");
    outTree->Branch("phi1",&phi1,"phi1/F");
    outTree->Branch("x",&x,"x/F");
    outTree->Branch("y",&y,"y/F");
    outTree->Branch("zeta",&zeta,"zeta/F");
    outTree->Branch("xF",&xF,"xF/F");
    outTree->Branch("pT1",&pT1,"pT1/F");
    outTree->Branch("pT2",&pT2,"pT2/F");
    outTree->Branch("Delta_phi",&Delta_phi,"Delta_phi/F");
    outTree->Branch("z1",&z1,"z1/F");
    outTree->Branch("z2",&z2,"z2/F");
    outTree->Branch("xF1",&xF1,"xF1/F");
    outTree->Branch("xF2",&xF2,"xF2/F");
    outTree->Branch("pTpT",&pTpT,"pTpT/F");
    outTree->Branch("Mx1",&Mx1,"Mx1/F");
    outTree->Branch("Mx2",&Mx2,"Mx2/F");
    outTree->Branch("Delta_eta",&Delta_eta,"Delta_eta/F");
    outTree->Branch("p1_p",&p1_p,"p1_p/F");
    outTree->Branch("p2_p",&p2_p,"p2_p/F");
    outTree->Branch("vz_e",&vz_e,"vz_e/F");
    outTree->Branch("vz_p1",&vz_p1,"vz_p1/F");
    outTree->Branch("vz_p2",&vz_p2,"vz_p2/F");
    outTree->Branch("eta2",&eta2,"eta2/F");
    outTree->Branch("Mx",&Mx,"Mx/F");



    for(int k=0; k<3966261; k++){

    fscanf(fp, "%f %f %f %f %f %f %f ", &runnum, &evnum, &helicity, &e_p, &eta1, &eta, &e_phi);

    fscanf(fp, " %f %f %f %f %f %f %f %lf ", &Q2, &W, &phi2, &phi1, &x, &y, &zeta, &xF);

    fscanf(fp, " %f %f %f %f %f %f %f %f %f ", &pT1, &pT2, &Delta_phi, &z1, &z2, &xF1, &xF2, &pTpT, &Mx1);

    fscanf(fp, " %f %f %f %f %f %f %f %f %f ", &Mx2, &Delta_eta, &p1_p, &p2_p, &vz_e, &vz_p1, &vz_p2, &eta2, &Mx);

    outTree->Fill();

    }


outTree->Write();
fclose(fp);
hfile->Write();
///////////////////////////////////////////////////////////////
gStyle->SetPadTopMargin(0.1);
gStyle->SetPadBottomMargin(0.15);
gStyle->SetPadLeftMargin(0.15);
gStyle->SetPadRightMargin(0.05);
TGaxis::SetMaxDigits(4);
///////////////////////////////////////////////////////////////
TCut NegHeli = ("helicity == -1");
TCut PosHeli = ("helicity == 1");
TCut DifHeli = ("(helicity == 1) - (helicity == -1)");
TCut SumHeli = ("(helicity == 1) + (helicity == -1)");
TCut Asym = ("((helicity == 1) - (helicity == -1)) / ((helicity == 1) + (helicity == -1))");
TString sinphi("2*sin(phi2)");
TString sinphi2("2*sin(phi1)");
TString sinphi3("2*sin(Delta_phi)");
TString sinphi4("(sin(Delta_phi))*(sin(Delta_phi))");
TString pTpTM1("pT1*pT2");
TString logpTpT ("log(pTpT)");
TCut Mxg = ("Mx>1 && y<0.75 && xF1<0 && xF2>0&& -10<vz_e&&vz_e<3 && 1.2<p2_p&&p2_p<3 && 0.5<p1_p");
TCut Mxa = ("Mx>0 && Mx<0.33");
TCut Mxb = ("Mx>0.33 && Mx<0.67");
TCut Mxc = ("Mx>0.67 && Mx<1.00");
TCut Mxd = ("Mx>1.00 && Mx<1.33");
TCut Mxe = ("Mx>1.33 && Mx<1.67");
TCut Mxf = ("Mx>1.67 && Mx<2.00");
///////////////////////////////////////////////////////////////
TCanvas*c01 = new TCanvas("c01", "PKplus", 1000,700);
c01->Divide(1,1);
c01->Print("Mxpk.pdf[");
TH1F*Mxpk = new TH1F("Mxpk","",500,0, 2.3);
c01->cd(1);
Mxpk->GetXaxis()->SetTitle("Missing Mass (GeV)");
Mxpk->GetXaxis()->SetTitleSize(0.1);
Mxpk->GetXaxis()->SetLabelSize(0.05);
Mxpk->GetXaxis()->SetTitleOffset(0.6);
Mxpk->GetYaxis()->SetTitle("Counts");
Mxpk->GetYaxis()->SetTitleSize(0.1);
Mxpk->GetYaxis()->SetLabelSize(0.05);
Mxpk->GetYaxis()->SetTitleOffset(0.6);
Mxpk->SetLineWidth(5);
Mxpk->SetStats(0);
outTree->Draw("Mx>>Mxpk");
///////////////////////////////////////////////////////////////
TCanvas*c02 = new TCanvas("c02", "PKplus", 1000,700);
c02->Divide(1,1);
c02->Print("Protonphi.pdf[");
TH1F*Pphi = new TH1F("Pphi","",500,0, 6.2);
c02->cd(1);
Pphi->GetXaxis()->SetTitle("Proton #phi (rad)");
Pphi->GetXaxis()->SetTitleSize(0.1);
Pphi->GetXaxis()->SetTitleOffset(0.6);
Pphi->GetXaxis()->SetLabelSize(0.05);
Pphi->GetYaxis()->SetTitle("Counts");
Pphi->GetYaxis()->SetTitleSize(0.1);
Pphi->GetYaxis()->SetLabelSize(0.05);
Pphi->GetYaxis()->SetTitleOffset(0.6);
Pphi->SetLineWidth(5);
Pphi->SetStats(0);
outTree->Draw("phi1>>Pphi");
///////////////////////////////////////////////////////////////
TCanvas*c03 = new TCanvas("c03", "PKplus", 1000,700);
c03->Divide(1,1);
c03->Print("Kaonphi.pdf[");
TH1F*Kphi = new TH1F("Kphi","",500,0, 6.2);
c03->cd(1);
Kphi->GetXaxis()->SetTitle("Kaon #phi (rad)");
Kphi->GetXaxis()->SetTitleSize(0.1);
Kphi->GetXaxis()->SetTitleOffset(0.6);
Kphi->GetXaxis()->SetLabelSize(0.05);
Kphi->GetYaxis()->SetTitle("Counts");
Kphi->GetYaxis()->SetTitleSize(0.1);
Kphi->GetYaxis()->SetLabelSize(0.05);
Kphi->GetYaxis()->SetTitleOffset(0.6);
Kphi->SetLineWidth(5);
Kphi->SetStats(0);
outTree->Draw("phi2>>Kphi");
///////////////////////////////////////////////////////////////
TCanvas*c04 = new TCanvas("c04", "PKplus", 1000,700);
c04->Divide(1,1);
c04->Print("Deltaphi.pdf[");
TH1F*Dphi = new TH1F("Dphi","",500,0, 6.2);
c04->cd(1);
Dphi->GetXaxis()->SetTitle("#Delta#phi (rad)");
Dphi->GetXaxis()->SetTitleSize(0.1);
Dphi->GetXaxis()->SetTitleOffset(0.6);
Dphi->GetXaxis()->SetLabelSize(0.05);
Dphi->GetYaxis()->SetTitle("Counts");
Dphi->GetYaxis()->SetTitleSize(0.1);
Dphi->GetYaxis()->SetLabelSize(0.05);
Dphi->GetYaxis()->SetTitleOffset(0.6);
Dphi->SetLineWidth(5);
Dphi->SetStats(0);
outTree->Draw("Delta_phi>>Dphi");
///////////////////////////////////////////////////////////////
TCanvas*c05 = new TCanvas("c05", "PKplus", 1000,700);
c05->Divide(1,1);
c05->Print("DeltaphiPH.pdf[");
TH1F*DphiPH = new TH1F("DphiPH","",500,0, 6.2);
c05->cd(1);
DphiPH->GetXaxis()->SetTitle("#Delta#phi (positive helicity)");
DphiPH->GetXaxis()->SetTitleSize(0.1);
DphiPH->GetXaxis()->SetTitleOffset(0.6);
DphiPH->GetXaxis()->SetLabelSize(0.05);
DphiPH->GetYaxis()->SetTitle("Counts");
DphiPH->GetYaxis()->SetTitleSize(0.1);
DphiPH->GetYaxis()->SetLabelSize(0.05);
DphiPH->GetYaxis()->SetTitleOffset(0.6);
DphiPH->SetLineWidth(5);
DphiPH->SetStats(0);
outTree->Draw("Delta_phi>>DphiPH", PosHeli && Mxg);
///////////////////////////////////////////////////////////////
TCanvas*c06 = new TCanvas("c06", "PKplus", 1000,700);
c06->Divide(1,1);
c06->Print("DeltaphiNH.pdf[");
TH1F*DphiNH = new TH1F("DphiNH","",500,0, 6.2);
c06->cd(1);
DphiNH->GetXaxis()->SetTitle("#Delta#phi (negative helicity)");
DphiNH->GetXaxis()->SetTitleSize(0.1);
DphiNH->GetXaxis()->SetTitleOffset(0.6);
DphiNH->GetXaxis()->SetLabelSize(0.05);
DphiNH->GetYaxis()->SetTitle("Counts");
DphiNH->GetYaxis()->SetTitleSize(0.1);
DphiNH->GetYaxis()->SetLabelSize(0.05);
DphiNH->GetYaxis()->SetTitleOffset(0.6);
DphiNH->SetLineWidth(5);
DphiNH->SetStats(0);
outTree->Draw("Delta_phi>>DphiNH", NegHeli && Mxg);
///////////////////////////////////////////////////////////////
TCanvas*c07 = new TCanvas("c07", "PKplus", 1000,700);
c07->Divide(1,1);
c07->Print("DeltaphiDif.pdf[");
TH1F*DphiDif = new TH1F("DphiDif","",500,0, 6.2);
c07->cd(1);
DphiDif->GetXaxis()->SetTitle("#Delta#phi (Difference Helicity)");
DphiDif->GetXaxis()->SetTitleSize(0.1);
DphiDif->GetXaxis()->SetTitleOffset(0.6);
DphiDif->GetXaxis()->SetLabelSize(0.05);
DphiDif->GetYaxis()->SetTitle("Counts");
DphiDif->GetYaxis()->SetTitleSize(0.1);
DphiDif->GetYaxis()->SetLabelSize(0.05);
DphiDif->GetYaxis()->SetTitleOffset(0.6);
DphiDif->SetLineWidth(5);
DphiDif->SetStats(0);
outTree->Draw("Delta_phi>>DphiDif", DifHeli && Mxg);
///////////////////////////////////////////////////////////////
TCanvas*c08 = new TCanvas("c08", "PKplus", 1000,700);
c08->Divide(1,1);
c08->Print("DeltaphiSum.pdf[");
TH1F*DphiSum = new TH1F("DphiSum","",500,0, 6.2);
c08->cd(1);
DphiSum->GetXaxis()->SetTitle("#Delta#phi (Sum Helicity)");
DphiSum->GetXaxis()->SetTitleSize(0.1);
DphiSum->GetXaxis()->SetTitleOffset(0.6);
DphiSum->GetXaxis()->SetLabelSize(0.05);
DphiSum->GetYaxis()->SetTitle("Counts");
DphiSum->GetYaxis()->SetTitleSize(0.1);
DphiSum->GetYaxis()->SetLabelSize(0.05);
DphiSum->GetYaxis()->SetTitleOffset(0.6);
DphiSum->SetLineWidth(5);
DphiSum->SetStats(0);
outTree->Draw("Delta_phi>>DphiSum", SumHeli && Mxg);
///////////////////////////////////////////////////////////////
TCanvas*c09 = new TCanvas("c09", "PKplus", 1000,700);
c09->Divide(1,1);
c09->Print("AsymNC.pdf[");
TH1F*AsymNC = new TH1F("AsymNC","",500,0, 6.2);
c09->cd(1);
AsymNC->GetXaxis()->SetTitle("#Delta#phi");
AsymNC->GetXaxis()->SetTitleSize(0.1);
AsymNC->GetXaxis()->SetTitleOffset(0.6);
AsymNC->GetXaxis()->SetLabelSize(0.05);
AsymNC->GetYaxis()->SetTitle("Asymmetry Value");
AsymNC->GetYaxis()->SetTitleSize(0.1);
AsymNC->GetYaxis()->SetLabelSize(0.05);
AsymNC->GetYaxis()->SetTitleOffset(0.6);
AsymNC->GetYaxis()->SetRangeUser(-0.03,0.03);
AsymNC->SetLineWidth(5);
AsymNC->SetStats(0);
outTree->Draw("Delta_phi>>AsymNC", Asym);
///////////////////////////////////////////////////////////////
TCanvas*c010 = new TCanvas("c010", "PKplus", 1000,700);
c010->Divide(1,1);
c010->Print("pTpTMx3D.pdf[");
TH2F*pTpTMx = new TH2F("pTpTMx","",500, 0,50,0,2.3);
c010->cd(1);
pTpTMx->GetXaxis()->SetTitle("p_{#perp} Kaon*p_{#perp} Proton");
pTpTMx->GetXaxis()->SetTitleSize(0.1);
pTpTMx->GetXaxis()->SetTitleOffset(0.6);
pTpTMx->GetXaxis()->SetLabelSize(0.05);
pTpTMx->GetYaxis()->SetTitle("Mx");
pTpTMx->GetYaxis()->SetTitleSize(0.1);
pTpTMx->GetYaxis()->SetLabelSize(0.05);
pTpTMx->GetYaxis()->SetTitleOffset(0.6);
pTpTMx->SetStats(0);
outTree->Draw("pTpT:Mx>>pTpTMx");
pTpTMx->Draw("SURF");
TCanvas*c021 = new TCanvas("c021", "PKplus", 1000,700);
c021->Divide(1,1);
c021->Print("pTpTMx.pdf[");
c021->cd(1);
pTpTMx->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c011 = new TCanvas("c011", "PKplus", 1000,700);
c011->Divide(1,1);
c011->Print("PtPt.pdf[");
TH1F*PtPt = new TH1F("PtPt","",500, 0,1);
c011->cd(1);
PtPt->GetXaxis()->SetTitle("p_{#perp} Kaon*p_{#perp} Proton");
PtPt->GetXaxis()->SetTitleSize(0.08);
PtPt->GetXaxis()->SetTitleOffset(0.6);
PtPt->GetXaxis()->SetLabelSize(0.05);
PtPt->GetYaxis()->SetTitle("Counts");
PtPt->GetYaxis()->SetTitleSize(0.1);
PtPt->GetYaxis()->SetTitleOffset(0.6);
PtPt->GetYaxis()->SetLabelSize(0.05);
PtPt->SetLineWidth(5);
PtPt->SetStats(0);
outTree->Draw("pTpT>>PtPt");
///////////////////////////////////////////////////////////////
TCanvas*c012 = new TCanvas("c012", "PKplus", 1000,700);
c012->Divide(1,1);
c012->Print("PtKaon.pdf[");
TH1F*PtKaon = new TH1F("PtKaon","",500, 0,1);
c012->cd(1);
PtKaon->GetXaxis()->SetTitle("p_{#perp} Kaon");
PtKaon->GetXaxis()->SetTitleSize(0.08);
PtKaon->GetXaxis()->SetTitleOffset(0.6);
PtKaon->GetXaxis()->SetLabelSize(0.05);
PtKaon->GetYaxis()->SetTitle("Counts");
PtKaon->GetYaxis()->SetTitleSize(0.1);
PtKaon->GetYaxis()->SetTitleOffset(0.6);
PtKaon->GetYaxis()->SetLabelSize(0.05);
PtKaon->SetLineWidth(5);
PtKaon->SetStats(0);
outTree->Draw("pT2>>PtKaon");
///////////////////////////////////////////////////////////////
TCanvas*c013 = new TCanvas("c013", "PKplus", 1000,700);
c013->Divide(1,1);
c013->Print("PtPro.pdf[");
TH1F*PtPro = new TH1F("PtPro","",500, 0,1);
c013->cd(1);
PtPro->GetXaxis()->SetTitle("p_{#perp} Proton");
PtPro->GetXaxis()->SetTitleSize(0.08);
PtPro->GetXaxis()->SetTitleOffset(0.6);
PtPro->GetXaxis()->SetLabelSize(0.05);
PtPro->GetYaxis()->SetTitle("Counts");
PtPro->GetYaxis()->SetTitleSize(0.1);
PtPro->GetYaxis()->SetTitleOffset(0.6);
PtPro->GetYaxis()->SetLabelSize(0.05);
PtPro->SetLineWidth(5);
PtPro->SetStats(0);
outTree->Draw("pT1>>PtPro");
///////////////////////////////////////////////////////////////
TCanvas*c014 = new TCanvas("c014", "PKplus", 1000,700);
c014->Divide(1,1);
c014->Print("PtSinP3D.pdf[");
TH2F*PtSinP = new TH2F("PtSinP","",100,0,50,-2,2);
c014->cd(1);
PtSinP->GetXaxis()->SetTitle("pT Proton");
PtSinP->GetXaxis()->SetTitleSize(0.1);
PtSinP->GetXaxis()->SetTitleOffset(0.6);
PtSinP->GetXaxis()->SetLabelSize(0.05);
PtSinP->GetYaxis()->SetTitle("2<sin(#phi_{proton})>");
PtSinP->GetYaxis()->SetTitleSize(0.1);
PtSinP->GetYaxis()->SetTitleOffset(0.6);
PtSinP->GetYaxis()->SetLabelSize(0.05);
PtSinP->SetStats(0);
outTree->Draw(sinphi+":pT1>>PtSinP");
PtSinP->Draw("SURF");
TCanvas*c018 = new TCanvas("c018", "PKplus", 1000,700);
c018->Divide(1,1);
c018->Print("PtSinP.pdf[");
c018->cd(1);
PtSinP->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c023 = new TCanvas("c023", "PKplus", 1000,700);
c023->Divide(1,1);
c023->Print("PtSinK3D.pdf[");
TH2F*PtSinK = new TH2F("PtSinK","",100,0,50,-2,2);
c023->cd(1);
PtSinK->GetXaxis()->SetTitle("pT Kaon");
PtSinK->GetXaxis()->SetTitleSize(0.1);
PtSinK->GetXaxis()->SetTitleOffset(0.6);
PtSinK->GetXaxis()->SetLabelSize(0.05);
PtSinK->GetYaxis()->SetTitle("2<sin(#phi_{kaon})>");
PtSinK->GetYaxis()->SetTitleSize(0.1);
PtSinK->GetYaxis()->SetTitleOffset(0.6);
PtSinK->GetYaxis()->SetLabelSize(0.05);
PtSinK->SetStats(0);
outTree->Draw(sinphi2+":pT2>>PtSinK");
PtSinK->Draw("SURF");
TCanvas*c024 = new TCanvas("c024", "PKplus", 1000,700);
c024->Divide(1,1);
c024->Print("PtSinK.pdf[");
c024->cd(1);
PtSinK->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c025 = new TCanvas("c025", "PKplus", 1000,700);
c025->Divide(1,1);
c025->Print("PtPtSin3D.pdf[");
TH2F*PtSinK = new TH2F("PtPtSin","",100,0,50,-2,2);
c025->cd(1);
PtPtSin->GetXaxis()->SetTitle("pTpT");
PtPtSin->GetXaxis()->SetTitleSize(0.1);
PtPtSin->GetXaxis()->SetTitleOffset(0.6);
PtPtSin->GetXaxis()->SetLabelSize(0.05);
PtPtSin->GetYaxis()->SetTitle("2<sin(#Delta#phi)>");
PtPtSin->GetYaxis()->SetTitleSize(0.1);
PtPtSin->GetYaxis()->SetTitleOffset(0.6);
PtPtSin->GetYaxis()->SetLabelSize(0.05);
PtPtSin->SetStats(0);
outTree->Draw(sinphi3+":pTpT>>PtPtSin");
PtPtSin->Draw("SURF");
TCanvas*c026 = new TCanvas("c026", "PKplus", 1000,700);
c026->Divide(1,1);
c026->Print("PtPtSin.pdf[");
c026->cd(1);
PtPtSin->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c015 = new TCanvas("c015", "PKplus", 1000,700);
c015->Divide(1,1);
c015->Print("MxPtSin.pdf[");
TH3F*MxPtSin = new TH3F("MxPtSin","", 10, 0, 1, 10, 0, 2.5, 10, -2, 2);
c015->cd(1);
MxPtSin->GetXaxis()->SetTitle("pT Proton");
MxPtSin->GetXaxis()->SetTitleSize(0.03);
MxPtSin->GetXaxis()->SetTitleOffset(1.8);
MxPtSin->GetXaxis()->SetLabelSize(0.04);
MxPtSin->GetYaxis()->SetTitle("Mx");
MxPtSin->GetYaxis()->SetTitleOffset(1.6);
MxPtSin->GetYaxis()->SetTitleSize(0.04);
MxPtSin->GetYaxis()->SetLabelSize(0.025);
MxPtSin->GetZaxis()->SetTitle("2<sin(#phi_{proton})>");
MxPtSin->GetZaxis()->SetTitleSize(0.04);
MxPtSin->GetZaxis()->SetLabelSize(0.025);
MxPtSin->SetStats(0);
outTree->Draw(sinphi+":Mx:pT1>>MxPtSin");
MxPtSin->Draw("BOX");
///////////////////////////////////////////////////////////////
TCanvas*c029 = new TCanvas("c029", "PKplus", 1000,700);
c029->Divide(1,1);
c029->Print("MxPtSinK.pdf[");
TH3F*MxPtSin = new TH3F("MxPtSinK","", 10, 0, 1, 10, 0, 2.5, 10, -2, 2);
c029->cd(1);
MxPtSinK->GetXaxis()->SetTitle("pT Kaon");
MxPtSinK->GetXaxis()->SetTitleSize(0.03);
MxPtSinK->GetXaxis()->SetTitleOffset(1.8);
MxPtSinK->GetXaxis()->SetLabelSize(0.04);
MxPtSinK->GetYaxis()->SetTitle("Mx");
MxPtSinK->GetYaxis()->SetTitleOffset(1.6);
MxPtSinK->GetYaxis()->SetTitleSize(0.04);
MxPtSinK->GetYaxis()->SetLabelSize(0.025);
MxPtSinK->GetZaxis()->SetTitle("2<sin(#phi_{kaon})>");
MxPtSinK->GetZaxis()->SetTitleSize(0.04);
MxPtSinK->GetZaxis()->SetLabelSize(0.025);
MxPtSinK->SetStats(0);
outTree->Draw(sinphi2+":Mx:pT2>>MxPtSinK");
MxPtSinK->Draw("BOX");
///////////////////////////////////////////////////////////////
TCanvas*c030 = new TCanvas("c030", "PKplus", 1000,700);
c030->Divide(1,1);
c030->Print("MxPtSinD.pdf[");
TH3F*MxPtSin = new TH3F("MxPtSinD","", 10, 0, 1, 10, 0, 2.5, 10, -2, 2);
c030->cd(1);
MxPtSinD->GetXaxis()->SetTitle("pTpT");
MxPtSinD->GetXaxis()->SetTitleSize(0.03);
MxPtSinD->GetXaxis()->SetTitleOffset(1.8);
MxPtSinD->GetXaxis()->SetLabelSize(0.04);
MxPtSinD->GetYaxis()->SetTitle("Mx");
MxPtSinD->GetYaxis()->SetTitleOffset(1.6);
MxPtSinD->GetYaxis()->SetTitleSize(0.04);
MxPtSinD->GetYaxis()->SetLabelSize(0.025);
MxPtSinD->GetZaxis()->SetTitle("2<sin(#Delta#phi)>");
MxPtSinD->GetZaxis()->SetTitleSize(0.04);
MxPtSinD->GetZaxis()->SetLabelSize(0.025);
MxPtSinD->SetStats(0);
outTree->Draw(sinphi3+":Mx:pTpT>>MxPtSinD");
MxPtSinD->Draw("BOX");
///////////////////////////////////////////////////////////////
TCanvas*c016 = new TCanvas("c016", "PKplus", 1000,700);
c016->Divide(1,1);
c016->Print("PtPMx3D.pdf[");
TH2F*PtPMx = new TH2F("PtPMx","",100, 0,50,0,2.2);
c016->cd(1);
PtPMx->GetXaxis()->SetTitle("pT Proton");
PtPMx->GetXaxis()->SetTitleSize(0.1);
PtPMx->GetXaxis()->SetTitleOffset(0.6);
PtPMx->GetXaxis()->SetLabelSize(0.05);
PtPMx->GetYaxis()->SetTitle("Mx");
PtPMx->GetYaxis()->SetTitleSize(0.1);
PtPMx->GetYaxis()->SetTitleOffset(0.6);
PtPMx->GetYaxis()->SetLabelSize(0.05);
PtPMx->SetStats(0);
outTree->Draw("Mx:pT1>>PtPMx");
PtPMx->Draw("SURF");
TCanvas*c019 = new TCanvas("c019", "PKplus", 1000,700);
c019->Divide(1,1);
c019->Print("PtPMx.pdf[");
c019->cd(1);
PtPMx->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c017 = new TCanvas("c017", "PKplus", 1000,700);
c017->Divide(1,1);
c017->Print("PtKMx3D.pdf[");
TH2F*PtKMx = new TH2F("PtKMx","",100, 0,50,0,2.2);
c017->cd(1);
PtKMx->GetXaxis()->SetTitle("p_{#perp} Kaon");
PtKMx->GetXaxis()->SetTitleSize(0.1);
PtKMx->GetXaxis()->SetTitleOffset(0.6);
PtKMx->GetXaxis()->SetLabelSize(0.05);
PtKMx->GetYaxis()->SetTitle("Mx");
PtKMx->GetYaxis()->SetTitleSize(0.1);
PtKMx->GetYaxis()->SetTitleOffset(0.6);
PtKMx->GetYaxis()->SetLabelSize(0.05);
PtKMx->SetStats(0);
outTree->Draw("Mx:pT2>>PtKMx");
PtKMx->Draw("SURF");
TCanvas*c020 = new TCanvas("c020", "PKplus", 1000,700);
c020->Divide(1,1);
c020->Print("PtKMx.pdf[");
c020->cd(1);
PtKMx->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c022 = new TCanvas("c022", "PKplus", 1000,700);
c022->Divide(1,1);
c022->Print("Sinphi.pdf[");
TH1F*Sinphi = new TH1F("Sinphi","",500, -2,2);
c022->cd(1);
Sinphi->GetXaxis()->SetTitle("2<sin(#phi_{proton})>");
Sinphi->GetXaxis()->SetTitleSize(0.1);
Sinphi->GetXaxis()->SetTitleOffset(0.6);
Sinphi->GetXaxis()->SetLabelSize(0.05);
Sinphi->GetYaxis()->SetTitle("Counts");
Sinphi->GetYaxis()->SetTitleSize(0.1);
Sinphi->GetYaxis()->SetTitleOffset(0.6);
Sinphi->GetYaxis()->SetLabelSize(0.05);
Sinphi->SetLineWidth(5);
Sinphi->SetStats(0);
outTree->Draw(sinphi+">>Sinphi");
///////////////////////////////////////////////////////////////
TCanvas*c027 = new TCanvas("c027", "PKplus", 1000,700);
c027->Divide(1,1);
c027->Print("SinphiK.pdf[");
TH1F*SinphiK = new TH1F("SinphiK","",500, -2,2);
c027->cd(1);
SinphiK->GetXaxis()->SetTitle("2<sin(#phi_{kaon})>");
SinphiK->GetXaxis()->SetTitleSize(0.1);
SinphiK->GetXaxis()->SetTitleOffset(0.6);
SinphiK->GetXaxis()->SetLabelSize(0.05);
SinphiK->GetYaxis()->SetTitle("Counts");
SinphiK->GetYaxis()->SetTitleSize(0.1);
SinphiK->GetYaxis()->SetTitleOffset(0.6);
SinphiK->GetYaxis()->SetLabelSize(0.05);
SinphiK->SetLineWidth(5);
SinphiK->SetStats(0);
outTree->Draw(sinphi2+">>SinphiK");
///////////////////////////////////////////////////////////////
TCanvas*c028 = new TCanvas("c028", "PKplus", 1000,700);
c028->Divide(1,1);
c028->Print("SinphiD.pdf[");
TH1F*SinphiD = new TH1F("SinphiD","",500, -2,2);
c028->cd(1);
SinphiD->GetXaxis()->SetTitle("2<sin(#Delta#phi)>");
SinphiD->GetXaxis()->SetTitleSize(0.1);
SinphiD->GetXaxis()->SetTitleOffset(0.6);
SinphiD->GetXaxis()->SetLabelSize(0.05);
SinphiD->GetYaxis()->SetTitle("Counts");
SinphiD->GetYaxis()->SetTitleSize(0.1);
SinphiD->GetYaxis()->SetTitleOffset(0.6);
SinphiD->GetYaxis()->SetLabelSize(0.05);
SinphiD->SetLineWidth(5);
SinphiD->SetStats(0);
outTree->Draw(sinphi3+">>SinphiD");
///////////////////////////////////////////////////////////////
TCanvas*c031 = new TCanvas("c031", "PKplus", 1000,700);
c031->Divide(1,1);
c031->Print("SinMx3D.pdf[");
TH2F*PtSinK = new TH2F("SinMx","",100,0, 2.5, 100,-2,2);
c031->cd(1);
SinMx->GetXaxis()->SetTitle("Mx");
SinMx->GetXaxis()->SetTitleSize(0.1);
SinMx->GetXaxis()->SetTitleOffset(0.6);
SinMx->GetXaxis()->SetLabelSize(0.05);
SinMx->GetYaxis()->SetTitle("2<sin(#Delta#phi)>");
SinMx->GetYaxis()->SetTitleSize(0.1);
SinMx->GetYaxis()->SetTitleOffset(0.6);
SinMx->GetYaxis()->SetLabelSize(0.05);
SinMx->SetStats(0);
outTree->Draw(sinphi3+":Mx>>SinMx");
SinMx->Draw("SURF");
TCanvas*c032 = new TCanvas("c032", "PKplus", 1000,700);
c032->Divide(1,1);
c032->Print("SinMx.pdf[");
c032->cd(1);
SinMx->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c033 = new TCanvas("c033", "PKplus", 1000,700);
c033->Divide(1,1);
c033->Print("pTpTM.pdf[");
TH1F*pTpTM = new TH1F("pTpTM","",500, 0,1);
c033->cd(1);
pTpTM->GetXaxis()->SetTitle("pTpT");
pTpTM->GetXaxis()->SetTitleSize(0.1);
pTpTM->GetXaxis()->SetTitleOffset(0.6);
pTpTM->GetXaxis()->SetLabelSize(0.05);
pTpTM->GetYaxis()->SetTitle("Counts");
pTpTM->GetYaxis()->SetTitleSize(0.1);
pTpTM->GetYaxis()->SetTitleOffset(0.6);
pTpTM->GetYaxis()->SetLabelSize(0.05);
pTpTM->SetLineWidth(5);
pTpTM->SetStats(0);
outTree->Draw(pTpTM1+">>pTpTM");
///////////////////////////////////////////////////////////////
TCanvas*c034 = new TCanvas("c034", "PKplus", 1000,700);
c034->Divide(1,1);
c034->Print("y.pdf[");
TH1F*Y = new TH1F("Y","",500, 0.2,0.8);
c034->cd(1);
Y->GetXaxis()->SetTitle("y");
Y->GetXaxis()->SetTitleSize(0.1);
Y->GetXaxis()->SetTitleOffset(0.6);
Y->GetXaxis()->SetLabelSize(0.05);
Y->GetYaxis()->SetTitle("Counts");
Y->GetYaxis()->SetTitleSize(0.1);
Y->GetYaxis()->SetTitleOffset(0.6);
Y->GetYaxis()->SetLabelSize(0.05);
Y->SetLineWidth(5);
Y->SetStats(0);
outTree->Draw("y>>Y");
///////////////////////////////////////////////////////////////
TCanvas*c035 = new TCanvas("c035", "PKplus", 1000,700);
c035->Divide(1,1);
c035->Print("xFPro.pdf[");
TH1F*xFPro = new TH1F("xFPro","",500, -1,0.6);
c035->cd(1);
xFPro->GetXaxis()->SetTitle("x-Feynman Proton");
xFPro->GetXaxis()->SetTitleSize(0.1);
xFPro->GetXaxis()->SetTitleOffset(0.6);
xFPro->GetXaxis()->SetLabelSize(0.05);
xFPro->GetYaxis()->SetTitle("Counts");
xFPro->GetYaxis()->SetTitleSize(0.1);
xFPro->GetYaxis()->SetTitleOffset(0.6);
xFPro->GetYaxis()->SetLabelSize(0.05);
xFPro->SetLineWidth(5);
xFPro->SetStats(0);
outTree->Draw("xF1>>xFPro");
///////////////////////////////////////////////////////////////
TCanvas*c036 = new TCanvas("c036", "PKplus", 1000,700);
c036->Divide(1,1);
c036->Print("xFKaon.pdf[");
TH1F*xFKaon = new TH1F("xFKaon","",500, -0.2,0.8);
c036->cd(1);
xFKaon->GetXaxis()->SetTitle("x-Feynman Kaon");
xFKaon->GetXaxis()->SetTitleSize(0.1);
xFKaon->GetXaxis()->SetTitleOffset(0.6);
xFKaon->GetXaxis()->SetLabelSize(0.05);
xFKaon->GetYaxis()->SetTitle("Counts");
xFKaon->GetYaxis()->SetTitleSize(0.1);
xFKaon->GetYaxis()->SetTitleOffset(0.6);
xFKaon->GetYaxis()->SetLabelSize(0.05);
xFKaon->SetLineWidth(5);
xFKaon->SetStats(0);
outTree->Draw("xF2>>xFKaon");
///////////////////////////////////////////////////////////////
TCanvas*c037 = new TCanvas("c037", "PKplus", 1000,700);
c037->Divide(1,1);
c037->Print("vzElec.pdf[");
TH1F*vzElec = new TH1F("vzElec","",500, -10,4);
c037->cd(1);
vzElec->GetXaxis()->SetTitle("Electron Vertex (cm)");
vzElec->GetXaxis()->SetTitleSize(0.1);
vzElec->GetXaxis()->SetTitleOffset(0.6);
vzElec->GetXaxis()->SetLabelSize(0.05);
vzElec->GetYaxis()->SetTitle("Counts");
vzElec->GetYaxis()->SetTitleSize(0.1);
vzElec->GetYaxis()->SetTitleOffset(0.6);
vzElec->GetYaxis()->SetLabelSize(0.05);
vzElec->SetLineWidth(5);
vzElec->SetStats(0);
outTree->Draw("vz_e>>vzElec");
///////////////////////////////////////////////////////////////
TCanvas*c038 = new TCanvas("c038", "PKplus", 1000,700);
c038->Divide(1,1);
c038->Print("Kaonmom.pdf[");
TH1F*Kaonmom = new TH1F("Kaonmom","",500, 0.5,8);
c038->cd(1);
Kaonmom->GetXaxis()->SetTitle("Kaon Momentum (GeV/c)");
Kaonmom->GetXaxis()->SetTitleSize(0.1);
Kaonmom->GetXaxis()->SetTitleOffset(0.6);
Kaonmom->GetXaxis()->SetLabelSize(0.05);
Kaonmom->GetYaxis()->SetTitle("Counts");
Kaonmom->GetYaxis()->SetTitleSize(0.1);
Kaonmom->GetYaxis()->SetTitleOffset(0.6);
Kaonmom->GetYaxis()->SetLabelSize(0.05);
Kaonmom->SetLineWidth(5);
Kaonmom->SetStats(0);
outTree->Draw("p2_p>>Kaonmom");
///////////////////////////////////////////////////////////////
TCanvas*c039 = new TCanvas("c039", "PKplus", 1000,700);
c039->Divide(1,1);
c039->Print("Promom.pdf[");
TH1F*Promom = new TH1F("Promom","",500, 0,5);
c039->cd(1);
Promom->GetXaxis()->SetTitle("Proton Momentum (GeV/c)");
Promom->GetXaxis()->SetTitleSize(0.1);
Promom->GetXaxis()->SetTitleOffset(0.6);
Promom->GetXaxis()->SetLabelSize(0.05);
Promom->GetYaxis()->SetTitle("Counts");
Promom->GetYaxis()->SetTitleSize(0.1);
Promom->GetYaxis()->SetTitleOffset(0.6);
Promom->GetYaxis()->SetLabelSize(0.05);
Promom->SetLineWidth(5);
Promom->SetStats(0);
outTree->Draw("p1_p>>Promom");
///////////////////////////////////////////////////////////////
TCanvas*c040 = new TCanvas("c040", "PKplus", 1000,700);
c040->Divide(1,1);
c040->Print("x.pdf[");
TH1F*X = new TH1F("X","",500, 0,1);
c040->cd(1);
X->GetXaxis()->SetTitle("x-bjorken");
X->GetXaxis()->SetTitleSize(0.1);
X->GetXaxis()->SetTitleOffset(0.6);
X->GetXaxis()->SetLabelSize(0.05);
X->GetYaxis()->SetTitle("Counts");
X->GetYaxis()->SetTitleSize(0.1);
X->GetYaxis()->SetTitleOffset(0.6);
X->GetYaxis()->SetLabelSize(0.05);
X->SetLineWidth(5);
X->SetStats(0);
outTree->Draw("x>>X");
    ///////////////////////////////////////////////////////////////
TCanvas*c041 = new TCanvas("c041", "PKplus",1000,700);
c041->Divide(1,1);
c041->Print("Q2.pdf[");
TH1F*Q = new TH1F("Q","",500, 0,8);
c041->cd(1);
Q->GetXaxis()->SetTitle("Q^{2}");
Q->GetXaxis()->SetTitleSize(0.1);
Q->GetXaxis()->SetTitleOffset(0.6);
Q->GetXaxis()->SetLabelSize(0.05);
Q->GetYaxis()->SetTitle("Counts");
Q->GetYaxis()->SetTitleSize(0.1);
Q->GetYaxis()->SetTitleOffset(0.6);
Q->GetYaxis()->SetLabelSize(0.05);
Q->SetLineWidth(5);
Q->SetStats(0);
outTree->Draw("Q2>>Q");
///////////////////////////////////////////////////////////////
TCanvas*c042 = new TCanvas("c042", "PKplus", 1000,700);
c042->Divide(1,1);
c042->Print("MxX.pdf[");
TH2F*MxX = new TH2F("MxX","",100,0.08,0.7,50,0,2.5);
c042->cd(1);
MxX->GetXaxis()->SetTitle("x");
MxX->GetXaxis()->SetTitleSize(0.1);
MxX->GetXaxis()->SetTitleOffset(0.6);
MxX->GetXaxis()->SetLabelSize(0.05);
MxX->GetYaxis()->SetTitle("Mx");
MxX->GetYaxis()->SetTitleSize(0.1);
MxX->GetYaxis()->SetTitleOffset(0.6);
MxX->GetYaxis()->SetLabelSize(0.05);
MxX->SetStats(0);
outTree->Draw("Mx:x>>MxX");
MxX->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c043 = new TCanvas("c043", "PKplus", 1000,700);
c043->Divide(1,1);
c043->Print("MxZ.pdf[");
TH2F*MxZ = new TH2F("MxZ","",100,0,2.5,50,0.24,1.6);
c043->cd(1);
MxZ->GetXaxis()->SetTitle("Mx");
MxZ->GetXaxis()->SetTitleSize(0.1);
MxZ->GetXaxis()->SetTitleOffset(0.6);
MxZ->GetXaxis()->SetLabelSize(0.05);
MxZ->GetYaxis()->SetTitle("z");
MxZ->GetYaxis()->SetTitleSize(0.1);
MxZ->GetYaxis()->SetTitleOffset(0.6);
MxZ->GetYaxis()->SetLabelSize(0.05);
MxZ->SetStats(0);
outTree->Draw("z:Mx>>MxZ");
MxZ->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c044 = new TCanvas("c044", "PKplus", 1000,700);
c044->Divide(1,1);
c044->Print("DPhipTpT.pdf[");
TH2F*DPhipTpT = new TH2F("DPhipTpT","",100,0,6.2,50,0,0.7);
c044->cd(1);
DPhipTpT->GetXaxis()->SetTitle("#Delta#phi");
DPhipTpT->GetXaxis()->SetTitleSize(0.1);
DPhipTpT->GetXaxis()->SetTitleOffset(0.6);
DPhipTpT->GetXaxis()->SetLabelSize(0.05);
DPhipTpT->GetYaxis()->SetTitle("pT-Kaon*pT-Proton");
DPhipTpT->GetYaxis()->SetTitleSize(0.1);
DPhipTpT->GetYaxis()->SetTitleOffset(0.6);
DPhipTpT->GetYaxis()->SetLabelSize(0.05);
DPhipTpT->SetStats(0);
outTree->Draw(pTpTM1+":Delta_phi>>DPhipTpT");
DPhipTpT->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c045 = new TCanvas("c045", "PKplus", 1000,700);
c045->Divide(1,1);
c045->Print("Q2X.pdf[");
TH2F*Q2X = new TH2F("Q2X","",100,1,7,50,0,0.8);
c045->cd(1);
Q2X->GetXaxis()->SetTitle("Q^{2}");
Q2X->GetXaxis()->SetTitleSize(0.1);
Q2X->GetXaxis()->SetTitleOffset(0.6);
Q2X->GetXaxis()->SetLabelSize(0.05);
Q2X->GetYaxis()->SetTitle("x");
Q2X->GetYaxis()->SetTitleSize(0.1);
Q2X->GetYaxis()->SetTitleOffset(0.6);
Q2X->GetYaxis()->SetLabelSize(0.05);
Q2X->SetStats(0);
outTree->Draw("x:Q2>>Q2X");
Q2X->Draw("COL");

///////////////////////////////////////////////////////////////
TCanvas*c046 = new TCanvas("c046", "PKplus", 1000,700);
c046->Divide(1,1);
c046->Print("Q2Z2.pdf[");
TH2F*Q2Z2 = new TH2F("Q2Z2","",100,1,7,50,0.1,0.9);
c046->cd(1);
Q2Z2->GetXaxis()->SetTitle("Q^{2}");
Q2Z2->GetXaxis()->SetTitleSize(0.1);
Q2Z2->GetXaxis()->SetTitleOffset(0.6);
Q2Z2->GetXaxis()->SetLabelSize(0.05);
Q2Z2->GetYaxis()->SetTitle("z-Kaon");
Q2Z2->GetYaxis()->SetTitleSize(0.1);
Q2Z2->GetYaxis()->SetTitleOffset(0.6);
Q2Z2->GetYaxis()->SetLabelSize(0.05);
Q2Z2->SetStats(0);
outTree->Draw("z2:Q2>>Q2Z2");
Q2Z2->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c047 = new TCanvas("c047", "PKplus", 1000,700);
c047->Divide(1,1);
c047->Print("Q2XF1.pdf[");
TH2F*Q2XF1 = new TH2F("Q2XF1","",100,1,7,50,-0.8,0.4);
c047->cd(1);
Q2XF1->GetXaxis()->SetTitle("Q^{2}");
Q2XF1->GetXaxis()->SetTitleSize(0.1);
Q2XF1->GetXaxis()->SetTitleOffset(0.6);
Q2XF1->GetXaxis()->SetLabelSize(0.05);
Q2XF1->GetYaxis()->SetTitle("X-Feynman-Proton");
Q2XF1->GetYaxis()->SetTitleSize(0.1);
Q2XF1->GetYaxis()->SetTitleOffset(0.6);
Q2XF1->GetYaxis()->SetLabelSize(0.05);
Q2XF1->SetStats(0);
outTree->Draw("xF1:Q2>>Q2XF1");
Q2XF1->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c048 = new TCanvas("c048", "PKplus", 1000,700);
c048->Divide(1,1);
c048->Print("Q2DPhi.pdf[");
TH2F*Q2DPhi = new TH2F("Q2DPhi","",100,1,7,50,0,6.2);
c048->cd(1);
Q2DPhi->GetXaxis()->SetTitle("Q^{2}");
Q2DPhi->GetXaxis()->SetTitleSize(0.1);
Q2DPhi->GetXaxis()->SetTitleOffset(0.6);
Q2DPhi->GetXaxis()->SetLabelSize(0.05);
Q2DPhi->GetYaxis()->SetTitle("#Delta#phi");
Q2DPhi->GetYaxis()->SetTitleSize(0.1);
Q2DPhi->GetYaxis()->SetTitleOffset(0.6);
Q2DPhi->GetYaxis()->SetLabelSize(0.05);
Q2DPhi->SetStats(0);
outTree->Draw("Delta_phi:Q2>>Q2DPhi");
Q2DPhi->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c049 = new TCanvas("c049", "PKplus", 1000,700);
c049->Divide(1,1);
c049->Print("Q2pTpT.pdf[");
TH2F*Q2pTpT = new TH2F("Q2pTpT","",100,1,7,50,0,0.7);
c049->cd(1);
Q2pTpT->GetXaxis()->SetTitle("Q^{2}");
Q2pTpT->GetXaxis()->SetTitleSize(0.1);
Q2pTpT->GetXaxis()->SetTitleOffset(0.6);
Q2pTpT->GetXaxis()->SetLabelSize(0.05);
Q2pTpT->GetYaxis()->SetTitle("pT-Kaon*pT-Proton");
Q2pTpT->GetYaxis()->SetTitleSize(0.1);
Q2pTpT->GetYaxis()->SetTitleOffset(0.6);
Q2pTpT->GetYaxis()->SetLabelSize(0.05);
Q2pTpT->SetStats(0);
outTree->Draw("pTpT:Q2>>Q2pTpT");
Q2pTpT->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c050 = new TCanvas("c050", "PKplus",1000,700);
c050->Divide(1,1);
c050->Print("Z2X.pdf[");
TH2F*Z2X = new TH2F("Z2X","",100,0.15,1,50,0.08,0.7);
c050->cd(1);
Z2X->GetXaxis()->SetTitle("z-Kaon");
Z2X->GetXaxis()->SetTitleSize(0.1);
Z2X->GetXaxis()->SetTitleOffset(0.6);
Z2X->GetXaxis()->SetLabelSize(0.05);
Z2X->GetYaxis()->SetTitle("x");
Z2X->GetYaxis()->SetTitleSize(0.1);
Z2X->GetYaxis()->SetTitleOffset(0.6);
Z2X->GetYaxis()->SetLabelSize(0.05);
Z2X->SetStats(0);
outTree->Draw("x:z2>>Z2X");
Z2X->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c051 = new TCanvas("c051", "PKplus", 1000,700);
c051->Divide(1,1);
c051->Print("Z2XF1.pdf[");
TH2F*Z2XF1 = new TH2F("Z2XF1","",100,0.15,1,50,-0.8,0.4);
c051->cd(1);
Z2XF1->GetXaxis()->SetTitle("z-Kaon");
Z2XF1->GetXaxis()->SetTitleSize(0.1);
Z2XF1->GetXaxis()->SetTitleOffset(0.6);
Z2XF1->GetXaxis()->SetLabelSize(0.05);
Z2XF1->GetYaxis()->SetTitle("x-Feynman-Proton");
Z2XF1->GetYaxis()->SetTitleSize(0.1);
Z2XF1->GetYaxis()->SetTitleOffset(0.6);
Z2XF1->GetYaxis()->SetLabelSize(0.05);
Z2XF1->SetStats(0);
outTree->Draw("xF1:z2>>Z2XF1");
Z2XF1->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c052 = new TCanvas("c052", "PKplus", 1000,700);
c052->Divide(1,1);
c052->Print("Z2DPhi.pdf[");
TH2F*Z2DPhi = new TH2F("Z2DPhi","",100,0.15,1,50,0,6.2);
c052->cd(1);
Z2DPhi->GetXaxis()->SetTitle("z-Kaon");
Z2DPhi->GetXaxis()->SetTitleSize(0.1);
Z2DPhi->GetXaxis()->SetTitleOffset(0.6);
Z2DPhi->GetXaxis()->SetLabelSize(0.05);
Z2DPhi->GetYaxis()->SetTitle("#Delta#phi");
Z2DPhi->GetYaxis()->SetTitleSize(0.1);
Z2DPhi->GetYaxis()->SetTitleOffset(0.6);
Z2DPhi->GetYaxis()->SetLabelSize(0.05);
Z2DPhi->SetStats(0);
outTree->Draw("Delta_phi:z2>>Z2DPhi");
Z2DPhi->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c053 = new TCanvas("c053", "PKplus", 1000,700);
c053->Divide(1,1);
c053->Print("Z2pTpT.pdf[");
TH2F*Z2pTpT = new TH2F("Z2pTpT","",100,0.15,1,50,0,0.7);
c053->cd(1);
Z2pTpT->GetXaxis()->SetTitle("z-Kaon");
Z2pTpT->GetXaxis()->SetTitleSize(0.1);
Z2pTpT->GetXaxis()->SetTitleOffset(0.6);
Z2pTpT->GetXaxis()->SetLabelSize(0.05);
Z2pTpT->GetYaxis()->SetTitle("pT-Kaon*pT-Proton");
Z2pTpT->GetYaxis()->SetTitleSize(0.1);
Z2pTpT->GetYaxis()->SetTitleOffset(0.6);
Z2pTpT->GetYaxis()->SetLabelSize(0.05);
Z2pTpT->SetStats(0);
outTree->Draw("pTpT:z2>>Z2pTpT");
Z2pTpT->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c054 = new TCanvas("c054", "PKplus", 1000,700);
c054->Divide(1,1);
c054->Print("XZ2.pdf[");
TH2F*XZ2 = new TH2F("XZ2","",100,0.08,0.7,50,0.15,1);
c054->cd(1);
XZ2->GetXaxis()->SetTitle("x");
XZ2->GetXaxis()->SetTitleSize(0.1);
XZ2->GetXaxis()->SetTitleOffset(0.6);
XZ2->GetXaxis()->SetLabelSize(0.05);
XZ2->GetYaxis()->SetTitle("z-Kaon");
XZ2->GetYaxis()->SetTitleSize(0.1);
XZ2->GetYaxis()->SetTitleOffset(0.6);
XZ2->GetYaxis()->SetLabelSize(0.05);
XZ2->SetStats(0);
outTree->Draw("z2:x>>XZ2");
XZ2->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c055 = new TCanvas("c055", "PKplus", 1000,700);
c055->Divide(1,1);
c055->Print("XXF1.pdf[");
TH2F*XXF1 = new TH2F("XXF1","",100,0.08,0.7,50,-0.8,0.4);
c055->cd(1);
XXF1->GetXaxis()->SetTitle("x");
XXF1->GetXaxis()->SetTitleSize(0.1);
XXF1->GetXaxis()->SetTitleOffset(0.6);
XXF1->GetXaxis()->SetLabelSize(0.05);
XXF1->GetYaxis()->SetTitle("x-Feynman-Proton");
XXF1->GetYaxis()->SetTitleSize(0.1);
XXF1->GetYaxis()->SetTitleOffset(0.6);
XXF1->GetYaxis()->SetLabelSize(0.05);
XXF1->SetStats(0);
outTree->Draw("xF1:x>>XXF1");
XXF1->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c056 = new TCanvas("c056", "PKplus", 1000,700);
c056->Divide(1,1);
c056->Print("XDPhi.pdf[");
TH2F*XDPhi = new TH2F("XDPhi","",100,0.08,0.7,50,0,6.2);
c056->cd(1);
XDPhi->GetXaxis()->SetTitle("x");
XDPhi->GetXaxis()->SetTitleSize(0.1);
XDPhi->GetXaxis()->SetTitleOffset(0.6);
XDPhi->GetXaxis()->SetLabelSize(0.05);
XDPhi->GetYaxis()->SetTitle("#Delta#phi");
XDPhi->GetYaxis()->SetTitleSize(0.1);
XDPhi->GetYaxis()->SetTitleOffset(0.6);
XDPhi->GetYaxis()->SetLabelSize(0.05);
XDPhi->SetStats(0);
outTree->Draw("Delta_phi:x>>XDPhi");
XDPhi->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c057 = new TCanvas("c057", "PKplus", 1000,700);
c057->Divide(1,1);
c057->Print("XpTpT.pdf[");
TH2F*XpTpT = new TH2F("XpTpT","",100,0.08,0.7,50,0,0.7);
c057->cd(1);
XpTpT->GetXaxis()->SetTitle("x");
XpTpT->GetXaxis()->SetTitleSize(0.1);
XpTpT->GetXaxis()->SetTitleOffset(0.6);
XpTpT->GetXaxis()->SetLabelSize(0.05);
XpTpT->GetYaxis()->SetTitle("pT-Kaon*pT-Proton");
XpTpT->GetYaxis()->SetTitleSize(0.1);
XpTpT->GetYaxis()->SetTitleOffset(0.6);
XpTpT->GetYaxis()->SetLabelSize(0.05);
XpTpT->SetStats(0);
outTree->Draw("pTpT:x>>XpTpT");
XpTpT->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c058 = new TCanvas("c058", "PKplus", 1000,700);
c058->Divide(1,1);
c058->Print("pTpTX.pdf[");
TH2F*pTpTX = new TH2F("pTpTX","",100,0,0.7,50,0.08,0.7);
c058->cd(1);
pTpTX->GetXaxis()->SetTitle("pT-Kaon*pT-Proton");
pTpTX->GetXaxis()->SetTitleSize(0.1);
pTpTX->GetXaxis()->SetTitleOffset(0.6);
pTpTX->GetXaxis()->SetLabelSize(0.05);
pTpTX->GetYaxis()->SetTitle("x");
pTpTX->GetYaxis()->SetTitleSize(0.1);
pTpTX->GetYaxis()->SetTitleOffset(0.6);
pTpTX->GetYaxis()->SetLabelSize(0.05);
pTpTX->SetStats(0);
outTree->Draw("x:pTpT>>pTpTX");
pTpTX->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c059 = new TCanvas("c059", "PKplus", 1000,700);
c059->Divide(1,1);
c059->Print("pTpTZ2.pdf[");
TH2F*pTpTZ2 = new TH2F("pTpTZ2","",100,0,0.6,50,0.15,1);
c059->cd(1);
pTpTZ2->GetXaxis()->SetTitle("pT-Kaon*pT-Proton");
pTpTZ2->GetXaxis()->SetTitleSize(0.1);
pTpTZ2->GetXaxis()->SetTitleOffset(0.6);
pTpTZ2->GetXaxis()->SetLabelSize(0.05);
pTpTZ2->GetYaxis()->SetTitle("z-Kaon");
pTpTZ2->GetYaxis()->SetTitleSize(0.1);
pTpTZ2->GetYaxis()->SetTitleOffset(0.6);
pTpTZ2->GetYaxis()->SetLabelSize(0.05);
pTpTZ2->SetStats(0);
outTree->Draw("z2:pTpT>>pTpTZ2");
pTpTZ2->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c060 = new TCanvas("c060", "PKplus", 1000,700);
c060->Divide(1,1);
c060->Print("pTpTXF1.pdf[");
TH2F*pTpTXF1 = new TH2F("pTpTXF1","",100,0,0.7,50,-0.8,0.4);
c060->cd(1);
pTpTXF1->GetXaxis()->SetTitle("pT-Kaon*pT-Proton");
pTpTXF1->GetXaxis()->SetTitleSize(0.1);
pTpTXF1->GetXaxis()->SetTitleOffset(0.6);
pTpTXF1->GetXaxis()->SetLabelSize(0.05);
pTpTXF1->GetYaxis()->SetTitle("x-Feynman-Proton");
pTpTXF1->GetYaxis()->SetTitleSize(0.1);
pTpTXF1->GetYaxis()->SetTitleOffset(0.6);
pTpTXF1->GetYaxis()->SetLabelSize(0.05);
pTpTXF1->SetStats(0);
outTree->Draw("xF1:pTpT>>pTpTXF1");
pTpTXF1->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c061 = new TCanvas("c061", "PKplus", 1000,700);
c061->Divide(1,1);
c061->Print("pTpTDPhi.pdf[");
TH2F*pTpTDPhi = new TH2F("pTpTDPhi","",100,0,0.7,50,0,6.2);
c061->cd(1);
pTpTDPhi->GetXaxis()->SetTitle("pT-Kaon*pT-Proton");
pTpTDPhi->GetXaxis()->SetTitleSize(0.1);
pTpTDPhi->GetXaxis()->SetTitleOffset(0.6);
pTpTDPhi->GetXaxis()->SetLabelSize(0.05);
pTpTDPhi->GetYaxis()->SetTitle("#Delta#phi");
pTpTDPhi->GetYaxis()->SetTitleSize(0.1);
pTpTDPhi->GetYaxis()->SetTitleOffset(0.6);
pTpTDPhi->GetYaxis()->SetLabelSize(0.05);
pTpTDPhi->SetStats(0);
outTree->Draw("Delta_phi:pTpT>>pTpTDPhi");
pTpTDPhi->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c062 = new TCanvas("c062", "PKplus", 1000,700);
c062->Divide(1,1);
c062->Print("XF1DPhi.pdf[");
TH2F*XF1DPhi = new TH2F("XF1DPhi","",100,-0.8,0.4,50,0,6.2);
c062->cd(1);
XF1DPhi->GetXaxis()->SetTitle("x-Feynman-Proton");
XF1DPhi->GetXaxis()->SetTitleSize(0.1);
XF1DPhi->GetXaxis()->SetTitleOffset(0.6);
XF1DPhi->GetXaxis()->SetLabelSize(0.05);
XF1DPhi->GetYaxis()->SetTitle("#Delta#phi");
XF1DPhi->GetYaxis()->SetTitleSize(0.1);
XF1DPhi->GetYaxis()->SetTitleOffset(0.6);
XF1DPhi->GetYaxis()->SetLabelSize(0.05);
XF1DPhi->SetStats(0);
outTree->Draw("Delta_phi:xF1>>XF1DPhi");
XF1DPhi->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c063 = new TCanvas("c063", "PKplus", 1000,700);
c063->Divide(1,1);
c063->Print("XF1pTpT.pdf[");
TH2F*XF1pTpT = new TH2F("XF1pTpT","",100,-0.8,0.4,50,0,0.6);
c063->cd(1);
XF1pTpT->GetXaxis()->SetTitle("x-Feynman-Proton");
XF1pTpT->GetXaxis()->SetTitleSize(0.1);
XF1pTpT->GetXaxis()->SetTitleOffset(0.6);
XF1pTpT->GetXaxis()->SetLabelSize(0.05);
XF1pTpT->GetYaxis()->SetTitle("pT-Kaon*pT-Proton");
XF1pTpT->GetYaxis()->SetTitleSize(0.1);
XF1pTpT->GetYaxis()->SetTitleOffset(0.6);
XF1pTpT->GetYaxis()->SetLabelSize(0.05);
XF1pTpT->SetStats(0);
outTree->Draw("pTpT:xF1>>XF1pTpT");
XF1pTpT->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c064 = new TCanvas("c064", "PKplus", 1000,700);
c064->Divide(1,1);
c064->Print("DPhiXF1.pdf[");
TH2F*DPhiXF1 = new TH2F("DPhiXF1","",100,0,6.2,50,-0.8,0.4);
c064->cd(1);
DPhiXF1->GetXaxis()->SetTitle("#Delta#phi");
DPhiXF1->GetXaxis()->SetTitleSize(0.1);
DPhiXF1->GetXaxis()->SetTitleOffset(0.6);
DPhiXF1->GetXaxis()->SetLabelSize(0.05);
DPhiXF1->GetYaxis()->SetTitle("x-Feynman-Proton");
DPhiXF1->GetYaxis()->SetTitleSize(0.1);
DPhiXF1->GetYaxis()->SetTitleOffset(0.6);
DPhiXF1->GetYaxis()->SetLabelSize(0.05);
DPhiXF1->SetStats(0);
outTree->Draw("xF1:Delta_phi>>DPhiXF1");
DPhiXF1->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c065 = new TCanvas("c065", "PKplus", 1000,700);
c065->Divide(1,1);
c065->Print("DPhipTpT.pdf[");
TH2F*DPhipTpT = new TH2F("DPhipTpT","",100,0,6.2,50,0,0.7);
c065->cd(1);
DPhipTpT->GetXaxis()->SetTitle("#Delta#phi");
DPhipTpT->GetXaxis()->SetTitleSize(0.1);
DPhipTpT->GetXaxis()->SetTitleOffset(0.6);
DPhipTpT->GetXaxis()->SetLabelSize(0.05);
DPhipTpT->GetYaxis()->SetTitle("pT-Kaon*pT-Proton");
DPhipTpT->GetYaxis()->SetTitleSize(0.1);
DPhipTpT->GetYaxis()->SetTitleOffset(0.6);
DPhipTpT->GetYaxis()->SetLabelSize(0.05);
DPhipTpT->SetStats(0);
outTree->Draw("pTpT:Delta_phi>>DPhipTpT");
DPhipTpT->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c066 = new TCanvas("c066", "PKplus", 1000,700);
c066->Divide(1,1);
c066->Print("MxZ2.pdf[");
TH2F*MxZ2 = new TH2F("MxZ2","",100,0,2.5,50,0.15,1);
c066->cd(1);
MxZ2->GetXaxis()->SetTitle("Mx");
MxZ2->GetXaxis()->SetTitleSize(0.1);
MxZ2->GetXaxis()->SetTitleOffset(0.6);
MxZ2->GetXaxis()->SetLabelSize(0.05);
MxZ2->GetYaxis()->SetTitle("z-Kaon");
MxZ2->GetYaxis()->SetTitleSize(0.1);
MxZ2->GetYaxis()->SetTitleOffset(0.6);
MxZ2->GetYaxis()->SetLabelSize(0.05);
MxZ2->SetStats(0);
outTree->Draw("z2:Mx>>MxZ2");
MxZ2->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c067 = new TCanvas("c067", "PKplus", 1000,700);
c067->Divide(1,1);
c067->Print("MxX.pdf[");
TH2F*MxX = new TH2F("MxX","",100,0,2.5,50,0.08,0.7);
c067->cd(1);
MxX->GetXaxis()->SetTitle("Mx");
MxX->GetXaxis()->SetTitleSize(0.1);
MxX->GetXaxis()->SetTitleOffset(0.6);
MxX->GetXaxis()->SetLabelSize(0.05);
MxX->GetYaxis()->SetTitle("x");
MxX->GetYaxis()->SetTitleSize(0.1);
MxX->GetYaxis()->SetTitleOffset(0.6);
MxX->GetYaxis()->SetLabelSize(0.05);
MxX->SetStats(0);
outTree->Draw("x:Mx>>MxX");
MxX->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c068 = new TCanvas("c068", "PKplus", 1000,700);
c068->Divide(1,1);
c068->Print("MxpTpT.pdf[");
TH2F*MxX = new TH2F("MxpTpT","",100,0,2.5,50,0,0.7);
c068->cd(1);
MxpTpT->GetXaxis()->SetTitle("Mx");
MxpTpT->GetXaxis()->SetTitleSize(0.1);
MxpTpT->GetXaxis()->SetTitleOffset(0.6);
MxpTpT->GetXaxis()->SetLabelSize(0.05);
MxpTpT->GetYaxis()->SetTitle("pT-Kaon*pT-Proton");
MxpTpT->GetYaxis()->SetTitleSize(0.1);
MxpTpT->GetYaxis()->SetTitleOffset(0.6);
MxpTpT->GetYaxis()->SetLabelSize(0.05);
MxpTpT->SetStats(0);
outTree->Draw("pTpT:Mx>>MxpTpT");
MxpTpT->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c069 = new TCanvas("c069", "PKplus", 1000,700);
c069->Divide(1,1);
c069->Print("Z2.pdf[");
TH1F*Z2 = new TH1F("Z2","",500, 0,1);
c069->cd(1);
Z2->GetXaxis()->SetTitle("z-Kaon");
Z2->GetXaxis()->SetTitleOffset(0.6);
Z2->GetXaxis()->SetTitleSize(0.1);
Z2->GetXaxis()->SetLabelSize(0.04);
Z2->GetYaxis()->SetTitle("Counts");
Z2->GetYaxis()->SetTitleOffset(0.6);
Z2->GetYaxis()->SetTitleSize(0.1);
Z2->GetYaxis()->SetLabelSize(0.04);
Z2->SetLineWidth(5);
Z2->SetStats(0);
outTree->Draw("z2>>Z2");
///////////////////////////////////////////////////////////////
TCanvas*c070 = new TCanvas("c070", "PKplus", 1000,700);
c070->Divide(1,1);
c070->Print("MxP2.pdf[");
TH2F*MxP2 = new TH2F("MxP2","",100,0,2.5,50,1,8);
c070->cd(1);
MxP2->GetXaxis()->SetTitle("Mx");
MxP2->GetXaxis()->SetTitleOffset(0.6);
MxP2->GetXaxis()->SetTitleSize(0.1);
MxP2->GetXaxis()->SetLabelSize(0.05);
MxP2->GetYaxis()->SetTitle("Kaon Momentum");
MxP2->GetYaxis()->SetTitleOffset(0.6);
MxP2->GetYaxis()->SetTitleSize(0.1);
MxP2->GetYaxis()->SetLabelSize(0.05);
MxP2->SetStats(0);
outTree->Draw("p2_p:Mx>>MxP2");
MxP2->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c071 = new TCanvas("c071", "PKplus", 1000,700);
c071->Divide(1,1);
c071->Print("Eta.pdf[");
TH1F*Eta = new TH1F("Eta","",500,-1,2);
c071->cd(1);
Eta->GetXaxis()->SetTitle("#eta");
Eta->GetXaxis()->SetTitleOffset(0.6);
Eta->GetXaxis()->SetTitleSize(0.1);
Eta->GetXaxis()->SetLabelSize(0.05);
Eta->GetYaxis()->SetTitle("Counts");
Eta->GetYaxis()->SetTitleOffset(0.6);
Eta->GetYaxis()->SetTitleSize(0.1);
Eta->GetYaxis()->SetLabelSize(0.05);
Eta->SetLineWidth(5);
Eta->SetStats(0);
outTree->Draw("eta>>Eta");
///////////////////////////////////////////////////////////////
TCanvas*c072 = new TCanvas("c072", "PKplus", 1000,700);
c072->Divide(1,1);
c072->Print("Z.pdf[");
TH1F*Z = new TH1F("Z","",500,0.24,1.6);
c072->cd(1);
Z->GetXaxis()->SetTitle("Zeta");
Z->GetXaxis()->SetTitleOffset(0.6);
Z->GetXaxis()->SetTitleSize(0.1);
Z->GetXaxis()->SetLabelSize(0.05);
Z->GetYaxis()->SetTitle("Counts");
Z->GetYaxis()->SetTitleOffset(0.6);
Z->GetYaxis()->SetTitleSize(0.1);
Z->GetYaxis()->SetLabelSize(0.05);
Z->SetLineWidth(5);
Z->SetStats(0);
outTree->Draw("zeta>>Z");
///////////////////////////////////////////////////////////////
TCanvas*c073 = new TCanvas("c073", "PKplus", 1000,700);
c073->Divide(1,1);
c073->Print("W.pdf[");
TH1F*w = new TH1F("w","",500,1,5);
c073->cd(1);
w->GetXaxis()->SetTitle("W");
w->GetXaxis()->SetTitleOffset(0.6);
w->GetXaxis()->SetTitleSize(0.1);
w->GetXaxis()->SetLabelSize(0.05);
w->GetYaxis()->SetTitle("Counts");
w->GetYaxis()->SetTitleOffset(0.6);
w->GetYaxis()->SetTitleSize(0.1);
w->GetYaxis()->SetLabelSize(0.05);
w->SetLineWidth(5);
w->SetStats(0);
outTree->Draw("W>>w");  
///////////////////////////////////////////////////////////////
TCanvas*c074 = new TCanvas("c074", "PKplus", 1000,700);
c074->Divide(1,1);
c074->Print("DPHIPHNH.pdf[");
c074->cd(1);
THStack *hs = new THStack("hs","");
hs->Add(DphiNH);
hs->Add(DphiPH);
hs->Draw("nostack");
hs->GetXaxis()->SetTitle("#Delta#phi");
hs->GetXaxis()->SetTitleSize(0.1);
hs->GetXaxis()->SetTitleOffset(0.6);
hs->GetXaxis()->SetLabelSize(0.05);
hs->GetYaxis()->SetTitle("Counts");
hs->GetYaxis()->SetTitleSize(0.1);
hs->GetYaxis()->SetLabelSize(0.05);
hs->GetYaxis()->SetTitleOffset(0.6);

   legend = new TLegend(0.15,0.7,0.3,.9);
   legend->AddEntry("DphiNH","#Delta#phi negative helicity","l");
   legend->AddEntry("DphiPH","#Delta#phi positive helicity","l");
  
   legend->Draw();
///////////////////////////////////////////////////////////////
TCanvas*c075 = new TCanvas("c075", "PKplus", 1000,700);
c075->Divide(1,1);
c075->Print("EMom.pdf[");
TH1F*ep = new TH1F("ep","",500,0,10);
c075->cd(1);
ep->GetXaxis()->SetTitle("Electron Momentum (GeV/c)");
ep->GetXaxis()->SetTitleOffset(0.6);
ep->GetXaxis()->SetTitleSize(0.1);
ep->GetXaxis()->SetLabelSize(0.05);
ep->GetYaxis()->SetTitle("Counts");
ep->GetYaxis()->SetTitleOffset(0.6);
ep->GetYaxis()->SetTitleSize(0.1);
ep->GetYaxis()->SetLabelSize(0.05);
ep->SetLineWidth(5);
ep->SetStats(0);
outTree->Draw("e_p>>ep");
///////////////////////////////////////////////////////////////
TCanvas*c076 = new TCanvas("c076", "PKplus", 1000,700);
c076->Divide(1,1);
c076->Print("vzProton.pdf[");
TH1F*vzp = new TH1F("vzp","",500,-11,3);
c076->cd(1);
vzp->GetXaxis()->SetTitle("Proton Vertex");
vzp->GetXaxis()->SetTitleOffset(0.6);
vzp->GetXaxis()->SetTitleSize(0.1);
vzp->GetXaxis()->SetLabelSize(0.05);
vzp->GetYaxis()->SetTitle("Counts");
vzp->GetYaxis()->SetTitleOffset(0.6);
vzp->GetYaxis()->SetTitleSize(0.1);
vzp->GetYaxis()->SetLabelSize(0.05);
vzp->SetLineWidth(5);
vzp->SetStats(0);
outTree->Draw("vz_p1>>vzp");
///////////////////////////////////////////////////////////////
TCanvas*c077 = new TCanvas("c077", "PKplus", 1000,700);
c077->Divide(1,1);
c077->Print("vzKaon.pdf[");
TH1F*vzk = new TH1F("vzk","",500,-13,10);
c077->cd(1);
vzk->GetXaxis()->SetTitle("Kaon Vertex");
vzk->GetXaxis()->SetTitleOffset(0.6);
vzk->GetXaxis()->SetTitleSize(0.1);
vzk->GetXaxis()->SetLabelSize(0.05);
vzk->GetYaxis()->SetTitle("Counts");
vzk->GetYaxis()->SetTitleOffset(0.6);
vzk->GetYaxis()->SetTitleSize(0.1);
vzk->GetYaxis()->SetLabelSize(0.05);
vzk->SetLineWidth(5);
vzk->SetStats(0);
outTree->Draw("vz_p2>>vzk");
///////////////////////////////////////////////////////////////
TCanvas*c078 = new TCanvas("c078", "PKplus", 1000,700);
c078->Divide(1,1);
c078->Print("MxDPhi.pdf[");
TH2F*MxDPhi = new TH2F("MxDPhi","",100,0,2.5,50,0,6.2);
c078->cd(1);
MxDPhi->GetXaxis()->SetTitle("Mx");
MxDPhi->GetXaxis()->SetTitleSize(0.1);
MxDPhi->GetXaxis()->SetTitleOffset(0.6);
MxDPhi->GetXaxis()->SetLabelSize(0.05);
MxDPhi->GetYaxis()->SetTitle("#Delta#phi");
MxDPhi->GetYaxis()->SetTitleSize(0.1);
MxDPhi->GetYaxis()->SetTitleOffset(0.6);
MxDPhi->GetYaxis()->SetLabelSize(0.05);
MxDPhi->SetStats(0);
outTree->Draw("Delta_phi:Mx>>MxDPhi");
MxDPhi->Draw("COL");
///////////////////////////////////////////////////////////////
TCanvas*c079 = new TCanvas("c079", "PKplus", 1000,700);
c079->Divide(1,1);
c079->Print("Sinphin.pdf[");
TH1F*Sinphin = new TH1F("Sinphin","",500, -2,2);
c079->cd(1);
Sinphin->GetXaxis()->SetTitle("2sin(#Delta#phi) (negative)");
Sinphin->GetXaxis()->SetTitleSize(0.1);
Sinphin->GetXaxis()->SetTitleOffset(0.6);
Sinphin->GetXaxis()->SetLabelSize(0.05);
Sinphin->GetYaxis()->SetTitle("Counts");
Sinphin->GetYaxis()->SetTitleSize(0.1);
Sinphin->GetYaxis()->SetTitleOffset(0.6);
Sinphin->GetYaxis()->SetLabelSize(0.05);
Sinphin->SetLineWidth(5);
Sinphin->SetStats(0);
outTree->Draw(sinphi3+">>Sinphin", NegHeli);
///////////////////////////////////////////////////////////////
TCanvas*c080 = new TCanvas("c080", "PKplus", 1000,700);
c080->Divide(1,1);
c080->Print("Sinphip.pdf[");
TH1F*Sinphip = new TH1F("Sinphip","",500, -2,2);
c080->cd(1);
Sinphip->GetXaxis()->SetTitle("2sin(#Delta#phi) (positive)");
Sinphip->GetXaxis()->SetTitleSize(0.1);
Sinphip->GetXaxis()->SetTitleOffset(0.6);
Sinphip->GetXaxis()->SetLabelSize(0.05);
Sinphip->GetYaxis()->SetTitle("Counts");
Sinphip->GetYaxis()->SetTitleSize(0.1);
Sinphip->GetYaxis()->SetTitleOffset(0.6);
Sinphip->GetYaxis()->SetLabelSize(0.05);
Sinphip->SetLineWidth(5);
Sinphip->SetStats(0);
outTree->Draw(sinphi3+">>Sinphip", PosHeli);
///////////////////////////////////////////////////////////////
TCanvas*c081 = new TCanvas("c081", "PKplus", 1000,700);
c081->Divide(1,1);
c081->Print("Sinphis.pdf[");
TH1F*Sinphip = new TH1F("Sinphis","",500, 0,1);
c081->cd(1);
Sinphis->GetXaxis()->SetTitle("sin^{2}(#Delta#phi)");
Sinphis->GetXaxis()->SetTitleSize(0.1);
Sinphis->GetXaxis()->SetTitleOffset(0.6);
Sinphis->GetXaxis()->SetLabelSize(0.05);
Sinphis->GetYaxis()->SetTitle("Counts");
Sinphis->GetYaxis()->SetTitleSize(0.1);
Sinphis->GetYaxis()->SetTitleOffset(0.6);
Sinphis->GetYaxis()->SetLabelSize(0.05);
Sinphis->SetLineWidth(5);
Sinphis->SetStats(0);
outTree->Draw(sinphi4+">>Sinphis");
///////////////////////////////////////////////////////////////
TCanvas*c082 = new TCanvas("c082", "PKplus", 1000,700);
c082->Divide(1,1);
c082->Print("ElecPhi.pdf[");
TH1F*ElecPhi = new TH1F("ElecPhi","",500, 0,6.25);
c082->cd(1);
ElecPhi->GetXaxis()->SetTitle("Electron #phi");
ElecPhi->GetXaxis()->SetTitleSize(0.1);
ElecPhi->GetXaxis()->SetTitleOffset(0.6);
ElecPhi->GetXaxis()->SetLabelSize(0.05);
ElecPhi->GetYaxis()->SetTitle("Counts");
ElecPhi->GetYaxis()->SetTitleSize(0.1);
ElecPhi->GetYaxis()->SetTitleOffset(0.6);
ElecPhi->GetYaxis()->SetLabelSize(0.05);
ElecPhi->SetLineWidth(5);
ElecPhi->SetStats(0);
outTree->Draw("e_phi>>ElecPhi");
///////////////////////////////////////////////////////////////
TCanvas*c083 = new TCanvas("c083", "PKplus", 1000,700);
c083->Divide(1,1);
c083->Print("logptpt.pdf[");
TH1F*logptpt = new TH1F("logptpt","",500, -10,10);
c083->cd(1);
logptpt->GetXaxis()->SetTitle("log(p_{#perp} Kaon*p_{#perp} Proton)");
logptpt->GetXaxis()->SetTitleSize(0.08);
logptpt->GetXaxis()->SetTitleOffset(0.6);
logptpt->GetXaxis()->SetLabelSize(0.05);
logptpt->GetYaxis()->SetTitle("Counts");
logptpt->GetYaxis()->SetTitleSize(0.1);
logptpt->GetYaxis()->SetTitleOffset(0.6);
logptpt->GetYaxis()->SetLabelSize(0.05);
logptpt->SetLineWidth(5);
logptpt->SetStats(0);
outTree->Draw(logpTpT+">>logptpt");
///////////////////////////////////////////////////////////////
c01->Print("Mxpk.pdf");
c01->Print("Mxpk.pdf]");
c02->Print("Protonphi.pdf");
c02->Print("Protonphi.pdf]");
c03->Print("Kaonphi.pdf");
c03->Print("Kaonphi.pdf]");
c04->Print("Deltaphi.pdf");
c04->Print("Deltaphi.pdf]");
c05->Print("DeltaphiPH.pdf");
c05->Print("DeltaphiPH.pdf]");
c06->Print("DeltaphiNH.pdf");
c06->Print("DeltaphiNH.pdf]");
c07->Print("DeltaphiDif.pdf");
c07->Print("DeltaphiDif.pdf]");
c08->Print("DeltaphiSum.pdf");
c08->Print("DeltaphiSum.pdf]");
c09->Print("AsymNC.pdf");
c09->Print("AsymNC.pdf]");
c010->Print("pTpTMx3D.pdf");
c010->Print("pTpTMx3D.pdf]");
c011->Print("PtPt.pdf");
c011->Print("PtPt.pdf]");
c012->Print("PtKaon.pdf");
c012->Print("PtKaon.pdf]");
c013->Print("PtPro.pdf");
c013->Print("PtPro.pdf]");
c014->Print("PtSinP3D.pdf");
c014->Print("PtSinP3D.pdf]");
c015->Print("MxPtSin.pdf");
c015->Print("MxPtSin.pdf]");
c016->Print("PtPMx3D.pdf");
c016->Print("PtPMx3D.pdf]");
c017->Print("PtKMx3D.pdf");
c017->Print("PtKMx3D.pdf]");
c018->Print("PtSinP.pdf");
c018->Print("PtSinP.pdf]");
c019->Print("PtPMx.pdf");
c019->Print("PtPMx.pdf]");
c020->Print("PtKMx.pdf");
c020->Print("PtKMx.pdf]");
c021->Print("pTpTMx.pdf");
c021->Print("pTpTMx.pdf]");
c022->Print("Sinphi.pdf");
c022->Print("Sinphi.pdf]");
c023->Print("PtSinK3D.pdf");
c023->Print("PtSinK3D.pdf]");
c024->Print("PtSinK.pdf");
c024->Print("PtSinK.pdf]");
c025->Print("PtPtSin3D.pdf");
c025->Print("PtPtSin3D.pdf]");
c026->Print("PtPtSin.pdf");
c026->Print("PtPtSin.pdf]");
c027->Print("SinphiK.pdf");
c027->Print("SinphiK.pdf]");
c028->Print("SinphiD.pdf");
c028->Print("SinphiD.pdf]");
c029->Print("MxPtSinK.pdf");
c029->Print("MxPtSinK.pdf]");
c030->Print("MxPtSinD.pdf");
c030->Print("MxPtSinD.pdf]");
c031->Print("SinMx3D.pdf");
c031->Print("SinMx3D.pdf]");
c032->Print("SinMx.pdf");
c032->Print("SinMx.pdf]");
c033->Print("pTpTM.pdf");
c033->Print("pTpTM.pdf]");
c034->Print("y.pdf");
c034->Print("y.pdf]");
c035->Print("xFPro.pdf");
c035->Print("xFPro.pdf]");
c036->Print("xFKaon.pdf");
c036->Print("xFKaon.pdf]");
c037->Print("vzElec.pdf");
c037->Print("vzElec.pdf]");
c038->Print("Kaonmom.pdf");
c038->Print("Kaonmom.pdf]");
c039->Print("Promom.pdf");
c039->Print("Promom.pdf]");
c040->Print("x.pdf");
c040->Print("x.pdf]");
c041->Print("Q2.pdf");
c041->Print("Q2.pdf]");
c042->Print("MxX.pdf");
c042->Print("MxX.pdf]");
c043->Print("MxZ.pdf");
c043->Print("MxZ.pdf]");
c044->Print("DPhipTpT.pdf");
c044->Print("DPhipTpT.pdf]");
c045->Print("Q2X.pdf");
c045->Print("Q2X.pdf]");
c046->Print("Q2Z2.pdf");
c046->Print("Q2Z2.pdf]");
c047->Print("Q2XF1.pdf");
c047->Print("Q2XF1.pdf]");
c048->Print("Q2DPhi.pdf");
c048->Print("Q2DPhi.pdf]");
c049->Print("Q2pTpT.pdf");
c049->Print("Q2pTpT.pdf]");
c050->Print("Z2X.pdf");
c050->Print("Z2X.pdf]");
c051->Print("Z2XF1.pdf");
c051->Print("Z2XF1.pdf]");
c052->Print("Z2DPhi.pdf");
c052->Print("Z2DPhi.pdf]");
c053->Print("Z2pTpT.pdf");
c053->Print("Z2pTpT.pdf]");
c054->Print("XZ2.pdf");
c054->Print("XZ2.pdf]");
c055->Print("XXF1.pdf");
c055->Print("XXF1.pdf]");
c056->Print("XDPhi.pdf");
c056->Print("XDPhi.pdf]");
c057->Print("XpTpT.pdf");
c057->Print("XpTpT.pdf]");
c058->Print("pTpTX.pdf");
c058->Print("pTpTX.pdf]");
c059->Print("pTpTZ2.pdf");
c059->Print("pTpTZ2.pdf]");
c060->Print("pTpTXF1.pdf");
c060->Print("pTpTXF1.pdf]");
c061->Print("pTpTDPhi.pdf");
c061->Print("pTpTDPhi.pdf]");
c062->Print("XF1DPhi.pdf");
c062->Print("XF1DPhi.pdf]");
c063->Print("XF1pTpT.pdf");
c063->Print("XF1pTpT.pdf]");
c064->Print("DPhiXF1.pdf");
c064->Print("DPhiXF1.pdf]");
c065->Print("DPhipTpT.pdf");
c065->Print("DPhipTpT.pdf]");
c066->Print("MxZ2.pdf");
c066->Print("MxZ2.pdf]");
c067->Print("MxX.pdf");
c067->Print("MxX.pdf]");
c068->Print("MxpTpT.pdf");
c068->Print("MxpTpT.pdf]");
c069->Print("Z2.pdf");
c069->Print("Z2.pdf]");
c070->Print("MxP2.pdf");
c070->Print("MxP2.pdf]");
c071->Print("Eta.pdf");
c071->Print("Eta.pdf]");
c072->Print("Z.pdf");
c072->Print("Z.pdf]");
c073->Print("W.pdf");
c073->Print("W.pdf]");
c074->Print("DPHIPHNH.pdf");
c074->Print("DPHIPHNH.pdf]");
c075->Print("EMom.pdf");
c075->Print("Emom.pdf]");
c076->Print("vzProton.pdf");
c076->Print("vzProton.pdf]");
c077->Print("vzKaon.pdf");
c077->Print("vzKaon.pdf]");
c078->Print("MxDPhi.pdf");
c078->Print("MxDPhi.pdf]");
c079->Print("Sinphin.pdf");
c079->Print("Sinphin.pdf]");
c080->Print("Sinphip.pdf");
c080->Print("Sinphip.pdf]");
c081->Print("Sinphis.pdf");
c081->Print("Sinphis.pdf]");
c082->Print("ElecPhi.pdf");
c082->Print("ElecPhi.pdf]");
c083->Print("logptpt.pdf");
c083->Print("logptpt.pdf]");
}






